object-cache.php
That is the max that memcached allows.
This is often due to incorrect data being passed in, like a timestamp, which often tends to be in the past (e.g. `YEAR_IN_SECONDS`) and therefore instantly expires.
https://github.com/memcached/memcached/wiki/Programming#expiration
=> Don't allow expiry > 30 days

object-cache.php
In case we need to track and handle errors in some way later on during the load process. We could trigger an action but the cache object is initialized before mu-plugins so we can't actually hook in.
/cc @simonwheatley re: https://github.com/Automattic/vip-go-mu-plugins/pull/386
=> Store connection errors in an object property

object-cache.php
Continued from #11; `absint` is not safe in certain contexts like when used with Batcache. Switch to `intval` instead.
=> Use php-native functions

object-cache.php
Props @david-binda
This changeset is applying a logic for keeping remote and local cache in sync based on the information we get from remote actions. In case a code calls remote add action and it fails, it's b/c there is already a value stored in memcache server. By removing the local, in memory, cache key-value pair, we make sure that the very next get call will make it to the remote server and will update the local cache with appropriate data.
The code is only removing the local cache in case it's value is equal to `false`, since if we were not doing so, various cache priming functions using add (eg.: update_site_cache, update_term_cache, update_post_cache) would introduced even more SQL queries that we are currently seeing due to alloptions.
=> Remove local empty cache in case the remove add action fails

object-cache.php, tests/test-object-cache.php
Sets a default color for commands in the stats colorizer function to prevent undefined index errors when a color is not defined. Also defines `green` for `get_multi` (to match `get`).
```
PHP Notice:  Undefined index: get_multi in /var/www/wp-content/object-cache.php on line 521
```
1. Pull PR
1. Navigate through site
1. Check Debug Bar panel for correct coloring in cache command names
1. Ensure there are no PHP notices for undefined index `get_multi`
=> Fix "undefined index" warning in stats colorizer for get_multi command

readme.txt
Props @paulschreiber for flagging this.
=> Bump "tested up to" to WordPress 5.4

object-cache.php, readme.txt, tests/test-object-cache.php
Update how we show the object-cache stats().
- Gather size and timing info for groups and individual calls.
- Differentiate between memcached server calls and local cache.
- Fix get_multi which was showing only a single group before.
~Edit: Needs rebase after https://github.com/Automattic/wp-memcached/pull/52 is merged. Should be minor.~ Done.
=> Gather and display better stats()

object-cache.php, readme.txt
object-cache.php might be used in places filters
haven't been loaded yet. Let's make the behavior explicit
and strip based on the presence of `key_salt`.
=> Always strip keys

object-cache.php
This will let us short-circuit the memcached request. The initial use-case here is to intercept hot keys to store them in a local apcu cache.
=> Add wp_cache_get_pre filter

object-cache.php
The list of links groups is floated, but for narrow windows, the list will wrap around the top stats in the Debug Bar panel. This PR clears the float, and increases the font size to make it a little more readable.
Before:
After:
=> Group list: Fix float and font size

.travis.yml, object-cache.php, tests/test-object-cache.php
Add flush_number replication to prevent accidental flush due to flush_number eviction, server rotation, etc.
Caches aren't flushed by telling memcached to flush itself because the memcached server could be hosting caches for multiple sites. So caches are flushed by changing the cache keys for only the site that needs flushing. Each site has its own flush_number which is automatically included in its cache keys. When the flush_number changes, all of the old keys become inaccessible, effectively flushing the cache for just that site.
Cache flushes could happen randomly when flush_number gets evicted. In setups with multiple cache servers, this can be prevented by storing the flush_number in all of the cache servers, keeping the values in sync, and always using the latest value.
Cache …
=> Add flush_number replication

.gitignore, .travis.yml, bin/test.sh, composer.json, phpunit.xml, tests/test-object-cache.php
This PR does several things:
* updates PHPUnit to 9.0 - this is what the recent WordPress expects; PHPUnit 5.x is too old; `phpunit.xml` had to be migrated;
* drops PHP 7.3 and adds PHP 8.0 to CI;
* adds support to run unit tests in a Docker container.
Bonuses:
* compatibility with PHP 8;
* fix risky tests (they are no longer risky)
=> Update PHPUnit, CI, add support for running tests in Docker

tests/bootstrap.php
PHPUnit refuses to generate a coverage report for `object-cache.php` moved to another directory ([example](https://travis-ci.org/github/Automattic/wp-memcached/jobs/774814300#L574)). This PR updates the test bootstrap to create `wp-content/object-cache.php` that `require_once` our `object-cache.php`. This way, the coverage is generated for the original file, and PHPUnit can process it.
=> Fix code coverage generation

.github/install-wp-tests.sh, .github/workflows/ci.yml, tests/test-object-cache.php
The CI takes now 34 seconds instead of 1 minute.
The speedup is achieved by using `services` (while MySQL starts up, we do other useful things like check out the source code or install dependencies) and by not using the `wp-test-runner` image (it takes some time to download it).
=> Speed up CI

object-cache.php, tests/test-object-cache.php
If `$server` is specified without the port (relying upon `memcache.default_port`), the code spits a notice "Undefined offset: 1". This PR fixes that notice.
=> Fix "Undefined offset: 1" when no port specified

object-cache.php, tests/test-object-cache.php
The semantics of `add()` is that it sets the key if it does not exist. However, this was not true for non-persistent groups. This PR fixes that.
=> add() should not overwrite non-persistent keys

object-cache.php, tests/test-object-cache.php
This PR adds support for `wp_cache_add_multiple()`, `wp_cache_delete_multiple()`, and `wp_cache_set_multiple()` functions introduced in WP 6.0.
However, because `Memcache` PHP extension does not support `multi` methods, this PR does not bring performance improvements.
Closes: #79
=> GH-79: Implement `wp_cache_(add|delete|set)_multiple`

object-cache.php, tests/test-object-cache.php
This PR adds support for the `wp_cache_get_multiple()` function introduced in WordPress 5.5.
Fixes #63
=> GH-63: Implement wp_cache_get_multiple()

object-cache.php
Added in core here 
https://github.com/WordPress/wordpress-develop/commit/c98f4c04db13a1c3db14345db4cff116dd01bf51
Simply clear the cache object property to clear memory.
=> Local cache flush

object-cache.php
On WordPress.org we use the object cache in places that sometimes operate with a minimal environment, and may not have apply_filters() loaded.
While this is a minimal change, and loading `plugin.php` for those environments might be ideal instead, the rest of the class appears to have minimal other dependencies.
=> Guard the call to apply_filters() incase it's unavailable
